name: "Theron Industries"
permalink: pretty
author: Theron Industries
email: hello@theronindustries.com
url: http://theronindustries.com

include: ['_pages']

exclude:
  - CNAME
  - editorconfig.txt
  - Gemfile
  - Gemfile.lock
  - README.md
  - RAKEFILE

gems:
  - jekyll-assets
  - uglifier
  - sass

assets:
  dirname: assets
  baseurl: /assets/
  cache: false

sources:
  - _assets/fonts
  - _assets/images
  - _assets/javascripts
  - _assets/stylesheets
